name: addrec_employee_management
version: 1.0.2+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.15
  iconsax: ^0.0.8
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.1
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  flutter_slidable: ^2.0.0
  animated_splash_screen: ^1.3.0
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  cached_network_image: ^3.2.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/svg/
  fonts:
    - family: bold
      fonts:
        - asset: font/Poppins-Bold.ttf
    - family: extraBold
      fonts:
        - asset: font/Poppins-ExtraBold.ttf
    - family: medium
      fonts:
        - asset: font/Poppins-Medium.ttf
    - family: regular
      fonts:
        - asset: font/Poppins-Regular.ttf
    - family: semiBold
      fonts:
        - asset: font/Poppins-SemiBold.ttf
  
# keytool -genkey -v -keystore onboarding-addrec.keystore -alias onboarding -keyalg RSA -keysize 2048 -validity 10000