// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1UjjKvyteDaZ6PsA2p_VjIt1u2yebRKg',
    appId: '1:893898850936:web:b7e3bdd25833b75101e38d',
    messagingSenderId: '893898850936',
    projectId: 'addrec-employee-management',
    authDomain: 'addrec-employee-management.firebaseapp.com',
    storageBucket: 'addrec-employee-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlb__eF4eO6M-tsJ0_JM6gKgR1EXgQRGE',
    appId: '1:893898850936:android:38486eed4d849aea01e38d',
    messagingSenderId: '893898850936',
    projectId: 'addrec-employee-management',
    storageBucket: 'addrec-employee-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNysWeassk_OJpJbPNw2PKKz0XdJTotg',
    appId: '1:893898850936:ios:22f1784b0ec09c9f01e38d',
    messagingSenderId: '893898850936',
    projectId: 'addrec-employee-management',
    storageBucket: 'addrec-employee-management.appspot.com',
    iosClientId: '893898850936-ulg6cgb15hq1cln34as0oa2tbpggn71c.apps.googleusercontent.com',
    iosBundleId: 'com.addrec.employeemenagement.addrecEmployeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNysWeassk_OJpJbPNw2PKKz0XdJTotg',
    appId: '1:893898850936:ios:22f1784b0ec09c9f01e38d',
    messagingSenderId: '893898850936',
    projectId: 'addrec-employee-management',
    storageBucket: 'addrec-employee-management.appspot.com',
    iosClientId: '893898850936-ulg6cgb15hq1cln34as0oa2tbpggn71c.apps.googleusercontent.com',
    iosBundleId: 'com.addrec.employeemenagement.addrecEmployeeManagement',
  );
}
